dist: xenial
compiler:
  - gcc
  - clang
language: c

before_script: autoreconf -vif

script:
  - sh build.sh
  - ./configure
  # VERBOSE=1 dumps the contents of the test suites logs to standard output.
  # -fsanitize=address enables https://github.com/google/sanitizers/wiki/AddressSanitizer
  - make check VERBOSE=1 CFLAGS=-fsanitize=address LDFLAGS=-fsanitize=address
  - make distcheck

addons:
  apt:
    packages:
    - autotools-dev
    - iptables-dev
    - libatasmart-dev
    - libcap-dev
    - libcurl4-gnutls-dev
    - libdbi0-dev
    - libesmtp-dev
    - libganglia1-dev
    - libgcrypt11-dev
    - libglib2.0-dev
    - libgps-dev
    - libhiredis-dev
    - libi2c-dev
    - libldap2-dev
    - libltdl-dev
    - liblua50-dev
    - liblua5.1-0-dev
    - liblua5.2-dev
    - libmemcached-dev
    - libmicrohttpd-dev
    - libmnl-dev
    - libmodbus-dev
    - libmosquitto-dev
    - libmysqlclient-dev
    - libnotify-dev
    - libopenipmi-dev
    - liboping-dev
    - libow-dev
    - libpcap-dev
    - libperl-dev
    - libpq-dev
    - libprotobuf-c0-dev
    - librabbitmq-dev
    - librdkafka-dev
    - libriemann-client-dev
    - librrd-dev
    - libsensors4-dev
    - libsigrok-dev
    - libsnmp-dev
    - libtokyocabinet-dev
    - libtokyotyrant-dev
    - libudev-dev
    - libupsclient-dev
    - libvarnish-dev
    - libvirt-dev
    - libxen-dev
    - libxml2-dev
    - libyajl-dev
    - linux-libc-dev
    - perl
    - protobuf-c-compiler
    - python3-dev
    - python-dev
    - xfslibs-dev
